### PR TITLE
add promised methods

### PR DESCRIPTION
**Pull request by vedi**
In our company we use your plugin (thank you for your effort). But we always patch it with the same code in order to make it working with promises.
I want to make it available in a module, and 1st though was to create own module, patching your code. But I think it's really bad from perspective of open source community, when we have such mess of patching modules. 
If you can accept this code, it'll be really helpful for us and (I think) for all community. If no, I'll go ahead with own module.

Thank you in advance.

### CODE REVIEW

**Comment by nono** [comment]
Hello,

Let's work together to make it happen. Having a way to work with promises without patching is welcomed.

On the patch itself, I'd like something more agnostic to the library used for promises. Bluebird is fine, bue the community may want to use to something else. And Bluebird is bigger than its alternative (correct me if I'm wrong).

I see two possibilities:

- I think I saw a proposal for nodejs to have a `global.Promise`, with the Promise implementation from v8 by default, but the application developer can overload with Bluebird or another Promise implementation. The goal is that most libs will used `global.Promise` and it will avoid conflicts between several Promise implementation.

- We can inject the promise implementation in the `options` of the constructor.

**Comment by nono** [comment]
For the record, this is how pouchdb handles Promises: https://www.npmjs.com/package/pouchdb-promise

**Comment by vedi** [comment]
ok, how does it look now?

**Comment by vedi** [comment]
FYI: Test failed because of lack of `Promise` in node.js v0.10. I'm not sure, how we can fix that in Travis: changing `engine` in `package.json`, or there is setting for this in Travis integration configs.

**Comment by frankrousseau** [comment]
I included your PR. I made changes about the API. Promises can be directly call with function name without giving any callback. The returned object is no more an array but a Javascript object that has two fieds, `res` and `body`.

Thank you for that feature and for the tests.

**Comment by nono** [comment]
@vedi nice, thanks for the time you've taken for this PR

**Comment by vedi** [comment]
thank you, guys!

**Pull request merged**
